spring.application.name=api-gateway
server.port=8084

spring.cloud.gateway.server.webmvc.routes[0].id=order-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/orders,/orders/**